# Site settings
title: ZeroFortySeven
email: me@ZeroFortySeven.com
description: > # this means to ignore newlines until "baseurl:"
  Kolijn Wolfaardt's blog, containing electronics and computer programming projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "zeroFortySeven.com" # the base hostname & protocol for your site
github_username:  KolijnWolfaardt
permalink: "/:year/:month/:title.html"
# Build settings
markdown: kramdown
